# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Data Model"
  url = "/DataModel"
  weight = 20
  identifier = "dom-id"

[[main]]
  name = "About SBOL"
  url = "/DataModel-about"
  weight = 5
  parent = "dom-id"

[[main]]
  name = "SBOL Specification"
  url = "/DataModel-Specification"
  weight = 10
  parent = "dom-id"

[[main]]
  name = "SBOL Libraries"
  url = "/libraries"
  weight = 15
  parent = "dom-id"

[[main]]
  name = "SBOL Ontology"
  url = "/ontology"
  weight = 20
  parent = "dom-id"

[[main]]
  name = "SBOL Converter"
  url = "https://converter.sbolstandard.org/"
  weight = 25
  parent = "dom-id"

[[main]]
  name = "SBOL Validator"
  url = "https://validator.sbolstandard.org/"
  weight = 30
  parent = "dom-id"

[[main]]
  name = "SBOL Examples"
  url = "/DataModel-Examples"
  weight = 35
  parent = "dom-id"

[[main]]
  name = "Visual"
  url = "/visual"
  weight = 25
  identifier = "visual-id"

[[main]]
  name = "About SBOL Visual"
  url = "/visual-about"
  weight = 5
  parent = "visual-id"

[[main]]
  name = "SBOL Visual Specification"
  url = "/visual-specification"
  weight = 10
  parent = "visual-id"

[[main]]
  name = "SBOL Visual Glyphs"
  url = "/visual-glyphs"
  weight = 15
  parent = "visual-id"

[[main]]
  name = "SBOL Visual Ontology"
  url = "/sbol-visual-ontology"
  weight = 20
  parent = "visual-id"

[[main]]
  name = "SBOL Visual Examples from papers"
  url = "/visual-examples"
  weight = 25
  parent = "visual-id"

[[main]]
  name = "SBOL Visual Examples from specification"
  url = "/visual-spec-examples"
  weight = 25
  parent = "visual-id"
  
[[main]]
  name = "Applications"
  url = "/applications"
  weight = 30

[[main]]
  name = "Publications"
  url = "/publication"
  weight = 40

[[main]]
  name = "Community"
  url = "/community"
  weight = 50
  identifier = "community-id"

[[main]]
  name = "About"
  url = "/community"
  weight = 5
  parent = "community-id"

[[main]]
  name = "Meetings"
  url = "/community-meetings"
  weight = 10
  parent = "community-id"

[[main]]
  name = "Outreach"
  url = "/community-outreach"
  weight = 15
  parent = "community-id"

[[main]]
  name = "Governance"
  url = "/community-governance"
  weight = 20
  parent = "community-id"

[[main]]
  name = "SBOL Industrial Consortium"
  url = "/sbol-industrial"
  weight = 25
  parent = "community-id"

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 55

[[main]]
  name = "Help"
  url = "/faq"
  weight = 60
  identifier = "help-id"

[[main]]
  name = "FAQ"
  url = "/faq"
  weight = 62
  parent = "help-id"

[[main]]
  name = "StackExchange"
  url = "https://bioinformatics.stackexchange.com/questions/tagged/sbol"
  weight = 64
  parent = "help-id"

[[main]]
  name = "About"
  url = "/about"
  weight = 70
  identifier = "about-id"

[[main]]
  name = "View Source"
  url = "https://synbiodex.github.io/SbolStandardWebsite/"
  weight = 75
  parent = "about-id"

[[main]]
  name = "Community Media"
  url = "https://github.com/SynBioDex/Community-Media"
  weight = 80
  parent = "about-id"  

[[main]]
  name = "Report an Issue"
  url = "https://github.com/SynBioDex/SbolStandardWebsite/issues"
  weight = 85
  parent = "about-id"

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
